settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: '正常'
  monitorLabelNotOperational: '故障'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-qikaile-tk
    name: 云生博客
    description: '心静思远，志行千里。'
    url: 'https://www.qikaile.tk/' 
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: pan-qikaile-tk
    name: 云生网盘
    description: '云生的个人网盘'
    url: 'https://pan.qikaile.tk/' 
    method: GET
    expectStatus: 200
   
  - id: box-tjys-ml
    name: 云生网址导航
    url: 'https://box.tjys.ml/' 
    method: GET
    expectStatus: 200
